# Generated by Django 5.1.1 on 2024-10-19 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('password', models.CharField(max_length=128, verbose_name='Password')),
                ('fname', models.CharField(max_length=30, verbose_name='First Name')),
                ('lname', models.CharField(max_length=30, verbose_name='Last Name')),
                ('number', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('address', models.TextField(verbose_name='Address')),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_species', models.CharField(max_length=30, unique=True, verbose_name='Pet Species')),
            ],
        ),
        migrations.CreateModel(
            name='AvailableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_slot_time', models.DateTimeField(unique=True, verbose_name='Available Slot Time')),
                ('slots_left', models.IntegerField(verbose_name='Slots Left')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_service', models.CharField(max_length=30, unique=True, verbose_name='Type of Service')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(null=True, verbose_name='Date/Time')),
                ('status', models.CharField(max_length=30, verbose_name='Status')),
                ('payment_status', models.CharField(max_length=15, verbose_name='Payment Status')),
                ('owners_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VetClinic.accounts', verbose_name="Owner's Name")),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VetClinic.animal', verbose_name='Species')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VetClinic.service', verbose_name='Service')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('pet_species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VetClinic.animal', verbose_name='Pet Species')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VetClinic.service', verbose_name='Service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VetClinic.accounts', verbose_name='User')),
            ],
        ),
    ]
