# Generated by Django 5.1.1 on 2024-10-22 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VetClinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='password',
            field=models.CharField(max_length=128, verbose_name='Password'),
        ),
    ]
